### ISSUE TITLE
Add `bool` example type

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/contexture-mongo#58]
We have it in contexture-elasticsearch. The main feature is that false would also match against null, undefined, and missing.

To exclude soft deleted records, right now users often do this:
```js
{
  key: 'isDeleted',
  field: 'isDeleted',
  type: 'facet',
  mode: 'exclude',
  values: [true],
}
```
which could become more semantic like this:

```js
{
  key: 'isDeleted',
  field: 'isDeleted',
  type: 'bool',
  value: false,
}
```
or even

```js
{
  key: 'isDeleted',
  field: 'isDeleted',
  type: 'bool',
}
```

**Comment by Akrion** [comment]
@daedalus28  we should probably close this now since #77 was merged.
